import type { SkillStage } from "../types/lesson";
import { WRITING_1_LESSONS } from "./stages/01-starter-0-2.5";
import { WRITING_2_LESSONS } from "./stages/02-elementary-2.5-3.5";
import { WRITING_3_LESSONS } from "./stages/03-pre-ielts-3.5-4.5";
import { WRITING_4_LESSONS } from "./stages/04-foundation-4.5-5.5";
import { WRITING_5_LESSONS } from "./stages/05-intermediate-5.5-6.5";
import { WRITING_6_LESSONS } from "./stages/06-upper-6.5-7.5";
import { WRITING_7_LESSONS } from "./stages/07-advanced-7.5-8.5";
import { WRITING_8_LESSONS } from "./stages/08-expert-8.5-9.0";
export const WRITING_CURRICULUM: SkillStage[] = [
  { id: "starter-0-2.5", title: "Starter — mất gốc Writing", skill: "writing", entryBand: 0, targetBand: 2.5, prerequisites: ["Không yêu cầu đầu vào; biết bảng chữ cái là lợi thế"], outcomes: ["Hoàn thành toàn bộ lesson và error log", "Đạt checkpoint ổn định ở target band", "Biết tự phân tích lỗi và chọn drill phù hợp"], studyTime: { lessonMinutes: 100, selfStudyMinutes: 80, sessionsPerWeek: 4, weeks: 12 }, lessons: WRITING_1_LESSONS, exitTest: ["1 bài timed/full-skill test", "1 vòng review lỗi", "1 retest sau tối thiểu 24 giờ"] },
  { id: "elementary-2.5-3.5", title: "Elementary Writing", skill: "writing", entryBand: 2.5, targetBand: 3.5, prerequisites: ["Hoàn thành Starter hoặc tương đương A1"], outcomes: ["Hoàn thành toàn bộ lesson và error log", "Đạt checkpoint ổn định ở target band", "Biết tự phân tích lỗi và chọn drill phù hợp"], studyTime: { lessonMinutes: 100, selfStudyMinutes: 80, sessionsPerWeek: 4, weeks: 10 }, lessons: WRITING_2_LESSONS, exitTest: ["1 bài timed/full-skill test", "1 vòng review lỗi", "1 retest sau tối thiểu 24 giờ"] },
  { id: "pre-ielts-3.5-4.5", title: "Pre-IELTS Writing", skill: "writing", entryBand: 3.5, targetBand: 4.5, prerequisites: ["Có thể tạo câu đơn và hiểu hướng dẫn tiếng Anh cơ bản"], outcomes: ["Hoàn thành toàn bộ lesson và error log", "Đạt checkpoint ổn định ở target band", "Biết tự phân tích lỗi và chọn drill phù hợp"], studyTime: { lessonMinutes: 100, selfStudyMinutes: 80, sessionsPerWeek: 4, weeks: 10 }, lessons: WRITING_3_LESSONS, exitTest: ["1 bài timed/full-skill test", "1 vòng review lỗi", "1 retest sau tối thiểu 24 giờ"] },
  { id: "foundation-4.5-5.5", title: "Foundation Writing", skill: "writing", entryBand: 4.5, targetBand: 5.5, prerequisites: ["Biết format IELTS và xử lý bài tập theo dạng"], outcomes: ["Hoàn thành toàn bộ lesson và error log", "Đạt checkpoint ổn định ở target band", "Biết tự phân tích lỗi và chọn drill phù hợp"], studyTime: { lessonMinutes: 100, selfStudyMinutes: 80, sessionsPerWeek: 4, weeks: 10 }, lessons: WRITING_4_LESSONS, exitTest: ["1 bài timed/full-skill test", "1 vòng review lỗi", "1 retest sau tối thiểu 24 giờ"] },
  { id: "intermediate-5.5-6.5", title: "Intermediate Writing", skill: "writing", entryBand: 5.5, targetBand: 6.5, prerequisites: ["Có nền ngữ pháp B1 tương đối ổn định"], outcomes: ["Hoàn thành toàn bộ lesson và error log", "Đạt checkpoint ổn định ở target band", "Biết tự phân tích lỗi và chọn drill phù hợp"], studyTime: { lessonMinutes: 100, selfStudyMinutes: 120, sessionsPerWeek: 5, weeks: 12 }, lessons: WRITING_5_LESSONS, exitTest: ["1 bài timed/full-skill test", "1 vòng review lỗi", "1 retest sau tối thiểu 24 giờ"] },
  { id: "upper-6.5-7.5", title: "Upper-Intermediate Writing", skill: "writing", entryBand: 6.5, targetBand: 7.5, prerequisites: ["Có thể hoàn thành full test trong thời gian quy định"], outcomes: ["Hoàn thành toàn bộ lesson và error log", "Đạt checkpoint ổn định ở target band", "Biết tự phân tích lỗi và chọn drill phù hợp"], studyTime: { lessonMinutes: 100, selfStudyMinutes: 120, sessionsPerWeek: 5, weeks: 12 }, lessons: WRITING_6_LESSONS, exitTest: ["1 bài timed/full-skill test", "1 vòng review lỗi", "1 retest sau tối thiểu 24 giờ"] },
  { id: "advanced-7.5-8.5", title: "Advanced Writing", skill: "writing", entryBand: 7.5, targetBand: 8.5, prerequisites: ["Band khoảng 7.0–7.5 ổn định trong nhiều đề"], outcomes: ["Hoàn thành toàn bộ lesson và error log", "Đạt checkpoint ổn định ở target band", "Biết tự phân tích lỗi và chọn drill phù hợp"], studyTime: { lessonMinutes: 100, selfStudyMinutes: 120, sessionsPerWeek: 5, weeks: 12 }, lessons: WRITING_7_LESSONS, exitTest: ["1 bài timed/full-skill test", "1 vòng review lỗi", "1 retest sau tối thiểu 24 giờ"] },
  { id: "expert-8.5-9.0", title: "Expert Writing", skill: "writing", entryBand: 8.5, targetBand: 9, prerequisites: ["Band khoảng 8.0–8.5 ổn định; mục tiêu tinh chỉnh lỗi hiếm"], outcomes: ["Hoàn thành toàn bộ lesson và error log", "Đạt checkpoint ổn định ở target band", "Biết tự phân tích lỗi và chọn drill phù hợp"], studyTime: { lessonMinutes: 100, selfStudyMinutes: 120, sessionsPerWeek: 5, weeks: 12 }, lessons: WRITING_8_LESSONS, exitTest: ["1 bài timed/full-skill test", "1 vòng review lỗi", "1 retest sau tối thiểu 24 giờ"] },
];
